### ISSUE TITLE
Terragrunt Docker example cannot reference local files

### ISSUE THREAD

**Issue by schlomo** [indeni/cloudrail-demo#49]
Problem: 
![image](https://user-images.githubusercontent.com/101384/109429728-92b5b200-79fd-11eb-8213-0b15ee5d7476.png)

Root cause:
`/data` is the working dir in the Docker container, but my TF plan references a file in my source space which is not available in the Docker container.

**Comment by yi2020** [comment]
Is it possible to reference the file using a relative path?

**Comment by schlomo** [comment]
No idea, `base_dir` is filled by Terragrunt. In any case, I don't see any harm in passing the host directory layout into the tool container. It ensures that everything below `pwd` works as expected as there is no path translation neccessary.

For a tool it is IMHO always better to not force the users into a certain behavior but to manage whatever they do.

**Comment by yi2020** [comment]
I agree fully with your last sentence. The change you proposed in #50 should work fine. I'd like to share with our developers to see if there's anything I'm missing.
